import Vue from "vue";
import AppDrag from "@/common/components/AppDrag.vue";
import AppDrop from "@/common/components/AppDrop.vue";
import BaseButton from "@/common/components/BaseButton.vue";
import BaseClose from "@/common/components/BaseClose.vue";
import BaseContent from "@/common/components/BaseContent.vue";
import BaseCounter from "@/common/components/BaseCounter.vue";
import BaseEditButton from "@/common/components/BaseEditButton.vue";
import BaseHeading from "@/common/components/BaseHeading.vue";
import BaseInput from "@/common/components/BaseInput.vue";
import BaseLogo from "@/common/components/BaseLogo.vue";
import BasePopup from "@/common/components/BasePopup.vue";
import BasePicture from "@/common/components/BasePicture.vue";
import BaseRadio from "@/common/components/BaseRadio.vue";
import BaseSelect from "@/common/components/BaseSelect.vue";
import BaseSheet from "@/common/components/BaseSheet.vue";
import BaseSubheading from "@/common/components/BaseSubheading.vue";

Vue.component("AppDrag", AppDrag);
Vue.component("AppDrop", AppDrop);
Vue.component("BaseButton", BaseButton);
Vue.component("BaseClose", BaseClose);
Vue.component("BaseContent", BaseContent);
Vue.component("BaseCounter", BaseCounter);
Vue.component("BaseEditButton", BaseEditButton);
Vue.component("BaseHeading", BaseHeading);
Vue.component("BaseInput", BaseInput);
Vue.component("BaseLogo", BaseLogo);
Vue.component("BasePopup", BasePopup);
Vue.component("BasePicture", BasePicture);
Vue.component("BaseRadio", BaseRadio);
Vue.component("BaseSelect", BaseSelect);
Vue.component("BaseSheet", BaseSheet);
Vue.component("BaseSubheading", BaseSubheading);
