import Vue from "vue";
import AppDrag from "@/common/components/AppDrag.vue";
import AppDrop from "@/common/components/AppDrop.vue";
import BlockButton from "@/common/components/BlockButton.vue";
import BlockClose from "@/common/components/BlockClose.vue";
import BlockContent from "@/common/components/BlockContent.vue";
import BlockCounter from "@/common/components/BlockCounter.vue";
import BlockEditButton from "@/common/components/BlockEditButton.vue";
import BlockHeading from "@/common/components/BlockHeading.vue";
import BlockInput from "@/common/components/BlockInput.vue";
import BlockLogo from "@/common/components/BlockLogo.vue";
import BlockPopup from "@/common/components/BlockPopup.vue";
import BlockPicture from "@/common/components/BlockPicture.vue";
import BlockRadio from "@/common/components/BlockRadio.vue";
import BlockSelect from "@/common/components/BlockSelect.vue";
import BlockSheet from "@/common/components/BlockSheet.vue";
import BlockSubheading from "@/common/components/BlockSubheading.vue";

Vue.component("AppDrag", AppDrag);
Vue.component("AppDrop", AppDrop);
Vue.component("BlockButton", BlockButton);
Vue.component("BlockClose", BlockClose);
Vue.component("BlockContent", BlockContent);
Vue.component("BlockCounter", BlockCounter);
Vue.component("BlockEditButton", BlockEditButton);
Vue.component("BlockHeading", BlockHeading);
Vue.component("BlockInput", BlockInput);
Vue.component("BlockLogo", BlockLogo);
Vue.component("BlockPopup", BlockPopup);
Vue.component("BlockPicture", BlockPicture);
Vue.component("BlockRadio", BlockRadio);
Vue.component("BlockSelect", BlockSelect);
Vue.component("BlockSheet", BlockSheet);
Vue.component("BlockSubheading", BlockSubheading);
