export const ADD_PIZZA = "ADD_PIZZA";
export const UPDATE_PIZZA = "UPDATE_PIZZA";
export const CHANGE_ORDER = "CHANGE_ORDER";
export const CHANGE_ADDITIONS = "CHANGE_ADDITIONS";
export const CHANGE_DELIVERY = "CHANGE_DELIVERY";
export const RESET_ORDER = "RESET_ORDER";
